---
abstract: 'A wrapper of selenium-server-standalone.jar'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Selenium-Server
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  LWP::UserAgent: 0
  Test::TCP: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/p5-Selenium-Server.git
version: 0.01
